var GAME_LEVELS = [
  ["                                                                                ",
   "       y                y                      y                          y     ",
   "             y                                                                  ",
   "                                   p                    y         y             ",
   "     p                      y                       o                           ",
   "                   y                      y                             p       ",
   "             p                                     xxx                          ",
   "                                     p          a                               ",
   " y              y        p                                 a          y         ",
   "                                 y         o   xxx              y          y    ",
   "       y                  o               a a        xxx                        ",
   "                   y      a                           v    p                xx  ",
   "  xx     p              xxxxx       a    xxxxx        o             p        x  ",
   "  x   y       ao     a xx   xxxx=o     o x   x                o o         o  x  ",
   "  x          xxxx   xxxx       xxxx   xxxx   xxxx              a             x  ",
   "  x         xx  x!!!x      y      x!!!x         xx a     a   xxxxx  s     l  x  ",
   "  x  @  o  xx   x!!!x             x!!!x          xxx     xxxxx   xxxxxx      x  ",
   "  xxxxxxxxxx    xxxxx             xxxxx      y     x!!!!!x            xxxxxxxx  ",
   "                       y                           x!!!!!x                      ",
   "        y                                          x!!!!!x         y            ",
   "                                                   xxxxxxx                      ",
   "   y          y                        y                             y          ",
   "                                                          y                     ",
   "                                                                                "],
  ["                                                                                      ",
   "  y                                                                                   ",
   "          x                                                         x                 ",
   "         x!x                                    y                  x!x          y     ",
   "      xxx!!!xxx    y                o                           xxx!!!xxx             ",
   "       x!!!!!x                    xxxxx                  y       x!!!!!x              ",
   "       x!x!x!x            a                                      x!x!x!x              ",
   "       xx v xx          xxxxx                                    xx v xx           y  ",
   "                p  o               p            o                                     ",
   "                   x   y                       xxx         y               y          ",
   "     y              x         x          oa          ao                               ",
   "                     x  a               xxxx        xxxx            y                 ",
   "                      xxxx       o                            o          a      o     ",
   "    xx         a                xxx               y          xxx        xxx     l     ",
   "    x         xxx                         a             a                             ",
   "    x                   o             o xxxx          xxxxx   y          y    xxxxx!!!",
   "    x @             y            a  xxxx!!!x       xxxx!!!x         a         x!!!!!!!",
   "    xxxxx   xxxxx       x       xxxxx!!!!!!x o        x!!!xx                 xx!!!!!!!",
   "          o     xx         y   xx!!!!!!!!!!xxxx       x!!!!xxxxx   xxx   xxxxx!!!!!!!!",
   "    y            xx          =xx!!!!!!!!!!!x  y     a x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "         xxx      xxxx  a  xxxx!!!!!!!!!!!!x       xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!!!!!!!!!x  s  o    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!x  o  x!!!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["      y                                       y                      y          ",
   "                  y                                                             ",
   "                               y                     y                          ",
   "   @                                                                            ",
   "  xxx           xxx                         y               xxx          y      ",
   "    x           x         a           o           a           x    xxx xxx      ",
   "    x     y     x                                       y     x   x!!!x!!!x     ",
   "    x           x        xxx    x   xxxxx   x    xxx          x    x!!!!!x      ",
   "    x o       a x                   x!!!x                   o x     x!!!x       ",
   "    xxxx     xxxxxxx         y       x!x              y    xxxx      x!x        ",
   "    x             y     xxxxx         v         xxxxx                 v         ",
   "    x y  xxx                                                                    ",
   "    x           xxxxxx         y             y         xxxxxx                   ",
   "    x a   =   o x    xxxx             y             xxxx  v       y             ",
   "    xxxx     xxxx       xxxx                     xxxx                     y     ",
   "       x!!!!!x             xxxx  p        y   xxxx           xxx                ",
   "       x!!!!!x   y                   xxx                                        ",
   "       x!!!!!x                 y                  a              xxx     lo     ",
   "       xxx!xxx        y               o                                         ",
   "  y       v                   xxx         y xxx       xxxxxxxxxx     xxxxxxxxx  ",
   "                              x   y           x   s   x!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               y       xxxxxxxx     xxxxx     xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "         a o       xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!xxx         xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                 ",
   "                                            y                                                    ",
   "        y                                                                 y             y        ",
   "                                 y                     y                                         ",
   "                                                                                                 ",
   "               y   y  yyy  y   y   y       y yyy y   y   y   y   y     y y                       ",
   "                y y  y   y y   y   y       y  y  yy  y   y   y   y    yyyyy                      ",
   "                 y   y   y y   y   y   y   y  y  y y y   y   y   y     yyy    y y                ",
   "     y           y   y   y y   y    y y y y   y  y  yy                  y    yyyyy       y       ",
   "                 y    yyy   yyy      y   y   yyy y   y   y   y   y            yyy                ",
   "                                                                               y                 ",
   "                y                p                                       y                       ",
   "                                              l          y                                       ",
   "          o             y                   x   x                                     o       y  ",
   "                                             x x                   p                             ",
   "                   y                          y                                                  ",
   "                                   xxxxx             xxxxx                    y                  ",
   "       xxxxx                                                                         xxxxx       ",
   "!     x              p    x                   a                      x                    x     !",
   "!!    x       y            xxx      y                  y          xxx                 y   x    !!",
   "!!!    x                                                                        p        x    !!!",
   "!!!!    x  s                                  @                       y              s  x    !!!!",
   "!!!!!    xxxxx     xxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx     xxxxx    !!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
